<?php
/**
 * @file
 * Hook implemenations for the Audit database logging module.
 */

/**
 * Implements hook_audit_log().
 */
function audit_log_db_audit_log(Auditlog $log) {
  $role_ids = $log->role_ids;

  drupal_write_record('audit_log', $log);
  foreach ($role_ids as $role_id) {
    $record = (object) array(
      'audit_log_id' => $log->id,
      'role_id' => $role_id,
    );
    drupal_write_record('audit_log_roles', $record);
  }
}
